version: "3.7"

services:
  duplicati:
    image: duplicati/duplicati
    container_name: duplicati
    volumes:
      - /:/source
      - /media/fantasio/backup:/destination
      - duplicati-data:/data
    expose:
      - 8200
    networks:
      - backup
      - reverse-proxy
    restart: unless-stopped

volumes:
  duplicati-data:
    name: duplicati-data

networks:
  backup:
    name: backup
  reverse-proxy:
    external: true
