version: "3.7"

services:
  duplicati:
    image: duplicati/duplicati
    volumes:
      - /:/source
      - /media/fantasio/backup:/destination
      - ./.duplicati/data:/data
    expose:
      - 8200
    restart: unless-stopped
